### ISSUE TITLE
Rotating the graph?

### ISSUE THREAD

**Issue by jteneycke** [seinecle/Plugins-for-Gephi#1]
I really enjoy your 3D force atlas plugin but I was wondering, is there a way to rotate the graph?

**Comment by nixos89** [comment]
There's alternative/simulation for it and it's by dragging. In Gephi version 0.9.2 you can do it by choosing "Dragging" option and configuring it (press blue "Configure" link) and choose desired Diameter on slider. Then select part of/whole graph you wish to rotate and that's it.
