### ISSUE TITLE
duration in seconds

### ISSUE THREAD

**Issue by pcomb** [seinecle/Plugins-for-Gephi#15]
I have a start and end date in oracle (coloumn type DATE). How shuold I capture this as followsing

YYYY-mm-dd hh24:mi:ss, YYYY-mm-dd hh24:mi:ss  ?

**Comment by seinecle** [comment]
You need a column that includes indications of time. Several possibilties:

1) Years or dates

Dates must be formatted in yyy-mm-dd: 2012-06-27
Years are just yyyy: 1968

 

2) Durations or single values:

- Durations are just a start and end time separated with a comma: 2012-06-27,2014-01-01
Or for a duration in years: 1958, 1999

- single values are, well: just a year: 1876 or just a date: 1879-03-19


Copied from here:
https://marketplace.gephi.org/plugin/excel-csv-converter-to-network/
