### ISSUE TITLE
Map does not overlap perfectly with network

### ISSUE THREAD

**Issue by deepakagrawal** [seinecle/Plugins-for-Gephi#20]
Hey I have nodes with Lat, long as attributes. When I combine the background map with the network, it doesn't overlap perfectly on the map.

**Comment by erlendos** [comment]
I seem to have the same problem. Do anyone know if there is a bug somewhere? 

Best regards
Erlend

**Comment by seinecle** [comment]
Hi,

It is a question of laying out first the map, then the network with the
GeoLayout. If the network is not perfectly aligned, re-run the Geolayout. I
often got the question in workshops and it was always solved by re-laying
out the map and the network in a different order.

-------------------------------------------------
Clement Levallois
Assistant professor EMLYON
Markets & Innovation Department
http://www.clementlevallois.net

direct line: +33(0)4 7833 7725
mobile: +33(0)6 5908 3392
Skype and Twitter: @seinecle

**Comment by erlendos** [comment]
Thank you for a quick answer. I have tried a couple of times now, just
adding two points close to Oslo in order to see what is wrong. So first I
lay out the Norway map, then I import a .csv file with only tre rows of
information: 1. company name; 2. lat; 3. lng. Everytime I get dots not
hitting in the map, like this:

Then I run the Geo Layout, but that only makes it worse and deletes the
lat/lng in the Data Laboratory. I think there is something fundemental I
have misunderstood with the procedure here. Do you have a link to a
step-by-step procedure?

Best regards
Erlend Osland Simensen
PhD fellow
University of Oslo
​

**Comment by seinecle** [comment]
Can you post your file, or a sample of it, if not confidential?

-------------------------------------------------
Clement Levallois
Assistant professor EMLYON
Markets & Innovation Department
http://www.clementlevallois.net

direct line: +33(0)4 7833 7725
mobile: +33(0)6 5908 3392
Skype and Twitter: @seinecle

**Comment by erlendos** [comment]
At the moment I am testing with  a test file, I have removed everything
that I thought could be an error. Maybe the format of the csv file is
wrong?

I attach it here.

Again, thank you very much for your help, really appreciate it.

Best
E

**Comment by seinecle** [comment]
not sure the file is attached?

**Comment by erlendos** [comment]
I attached the csv file. Bute here is both.

**Comment by seinecle** [comment]
Sorry I might be unfamiliar with Github issues, but I think that when you reply by email and attach a file, this file gets stripped from the msg so I don't receive it. Please send it to clementlevallois@gmail.com

**Comment by seinecle** [comment]
Solved: the problem was that commas were used in the long and lat. These columns need *dots* to express decimals.

**Comment by BiChenMIGRATION** [comment]
你要注意你的数据中经度的命名为"lng"而不是我们习惯的"lon",纬度命名"lat",同时先map of countries然后geo layout
You should pay attention to the longitude named "lng" in your data instead of the "lon" we are used to, and the latitude named "lat", and map of countries first and then geo layout

**Comment by BiChenMIGRATION** [comment]
You should pay attention to the longitude named "lng" in your data instead of the "lon" we are used to, and the latitude named "lat", and map of countries first and then geo layout
