### ISSUE TITLE
Create a network of more than two types of entities

### ISSUE THREAD

**Issue by dee-gee** [seinecle/Plugins-for-Gephi#21]
Hello,
Thanks for creating this brilliant plug-in. However, my immediate need requires three entities. Using your example, what I am aiming for would involve three entities, 'Author', 'Book' and 'Literary Agent'. Can you update your plug-in to accommodate three entities? Is there any other method of doing this, even without your plug-in?

**Comment by seinecle** [comment]
Hi,
Sorry the plugin won't extend to 3 entities in the forthseeable future. Importind a network through a csv file, where each node is categorized as one type of agent, is always possible (check simply: https://github.com/gephi/gephi/wiki/Import-CSV-Data)
