### ISSUE TITLE
[French] Add some map information about a small territory

### ISSUE THREAD

**Issue by AmauryVanEspen** [seinecle/Plugins-for-Gephi#22]
Cher M. Levallois,

j'explore avec grand intérêt votre site internet et plus particulièrement vos contributions à Gephi http://www.clementlevallois.net/portfolio.html
Je m'intéresse plus particulièrement à votre article : https://exploreyourdata.wordpress.com/2013/09/24/new-gephi-plugin-add-background-maps-to-your-networks/
concernant la possibilité d'ajouter en arrière plan, les "limites territoriales".
Je recherche notamment sur GitHub https://github.com/seinecle/Plugins-for-Gephi/tree/master/MapOfCountries
la documentation me permettant de me concentrer sur un périmètre géographique très petit, local, tel que la ville de Lille et ses quartiers.

après exploration rapide des ressources, je crois comprendre que les "cartes" sont issues de http://thematicmapping.org/downloads/world_borders.php et http://www.mappinghacks.com/data/
je suis en relation avec l'IGN français, afin d'essayer d'obtenir des informations sur le périmètre géographique qui m'intéresse afin de pouvoir les importer dans GEPHI,
je crois comprendre que vous avez fait de même pour le périmètre de l'Australie

peut être existe t-il déjà un jeu de données pour le territoire que je recherche, auriez vous des pistes à m'indiquer éventuellement, pour le trouver, ou sur le moyen de le créer de l'utiliser dans votre plugin ?

je vous remercie de votre aimable collaboration

Cordialement

Amaury

**Comment by seinecle** [comment]
Bonjour,
A ce stade il faut code en Java pour étendre le plugin à d'autres régions géographiques. J'ai un projet inachevé pour inclure toutes les régions administratives d'Europe, y compris les départements français. Malheureusement sans date de livraison prévue.

**Comment by AmauryVanEspen** [comment]
Bonjour,
en fait, j'en arrive au stade où le compilateur Java plante (Eclipse J2E) parce qu'il manque des composants microsoft ...
J'aurai apprécié réussir à compiler proprement pour mettre le résultat de mon travail à disposition

**Comment by seinecle** [comment]
Gephi est developpé sur la plateforme Netbeans, je recommande donc vraiment
de travailler sur Netbeans.

-------------------------------------------------
Clement Levallois
Assistant professor EMLYON
Markets & Innovation Department
http://www.clementlevallois.net

direct line: +33(0)4 7833 7725
mobile: +33(0)6 5908 3392
Skype and Twitter: @seinecle

2015-07-13 10:43 GMT+02:00 Amaury Van Espen <notifications@github.com>:

**Comment by AmauryVanEspen** [comment]
Bonsoir,

pourriez vous m'assister dans cette procédure une première fois ? il semble que je ne m'en sorte pas seul à cette étape :-(

Je vous remercie

Amaury
