### ISSUE TITLE
ExcelCsvImporter - Gephi 0.9.+ Compatibility

### ISSUE THREAD

**Issue by NDuma** [seinecle/Plugins-for-Gephi#26]
"The installer will download, verify and then install the selected plugins.
- Some plugins require plugin org.gephi.data.attributes.api to be installed.
  The plugin org.gephi.data.attributes.api is requested in version 0.8.2.  
  The following plugin is affected:       
  Convert Excel and csv files to networks 
- Some plugins require plugin org.gephi.dynamic.api to be installed.
  The plugin org.gephi.dynamic.api is requested in version 0.8.2.  
  The following plugin is affected:       
  Convert Excel and csv files to networks 
- Some plugins require plugin org.gephi.spigot.plugin to be installed.
  The plugin org.gephi.spigot.plugin is requested in version 0.8.2.  
  The following plugin is affected:       
  Convert Excel and csv files to networks

Some Plugins not installed to avoid potential installation problems."
### 'Next' is not an option; opening Issue for investigation of "Potential Installation Problems."

![Gephi Plugin Installer](https://cloud.githubusercontent.com/assets/8163869/12440676/ddc2f620-bef2-11e5-9288-6cd2f93fde70.png)

**Comment by kristinara** [comment]
I hope this gets resolved soon!

**Comment by eduramiba** [comment]
Related pull request for 0.9.1 https://github.com/gephi/gephi-plugins/pull/101

**Comment by eduramiba** [comment]
The plugin is now available in Gephi 0.9.1
