### ISSUE TITLE
Update GiveColorToNodes for Gephi 0.9

### ISSUE THREAD

**Issue by Farewe** [seinecle/Plugins-for-Gephi#27]
The  plugin GiveColorToNodes is not available for Gephi 0.9. This one is so useful it has become essential to my work!
Any chance you might update this plugin soon? ;)

**Comment by eduramiba** [comment]
Related pull request for 0.9.1 https://github.com/gephi/gephi-plugins/pull/102

**Comment by seinecle** [comment]
Now available.
