### ISSUE TITLE
Install of Maps of Countries 1.4.1 from Marketplace not working in Gephi 0.9.1

### ISSUE THREAD

**Issue by gorbynet** [seinecle/Plugins-for-Gephi#28]
Hi,
I'm really interested in using Maps of Countries in Gephi 0.9.1. The application is installed without internet privileges on the company network, so I can't download directly within Gephi. If I download the latest NBM (v1.4.1) from Gephi Marketplace and try to install from a local drive, I get this error message:

Some plugins require plugin org.gephi.data.attributes.api to be installed.
The plugin org.gephi.data.attributes.api is requested in version 0.8.2.  The following plugin is affected:       Map Of Countries 
Some plugins require plugin org.gephi.dynamic.api to be installed.
The plugin org.gephi.dynamic.api is requested in version 0.8.2.  The following plugin is affected:       Map Of Countries

Is there a version of Maps of Countries compatible with Gephi 0.9.1 available?

**Comment by seinecle** [comment]
working on upgrading it to 0.9.1 asap

**Comment by gorbynet** [comment]
Thanks Clement.
I found a workaround, which is to render the map in 0.8.2 and export the resulting graph as a GEXF file. This GEXF can be imported into 0.9.1 fine (although it generates a message about the GEXF format being deprecated).
