### ISSUE TITLE
Using Map and Edge Filters

### ISSUE THREAD

**Issue by fiszermane** [seinecle/Plugins-for-Gephi#30]
Hello.

First of all thank you so much for building this plugin. It's incredibly useful.

If I build a map with nodes and edges, each time I use filters with edges, the map disappears. I was just wondering if there is a way to filter edges but disallow these filters to touch the nodes/edges that the map is created with. Wasn't able to find this info in the guide.

Thank you,

Eze

**Comment by seinecle** [comment]
It's on its way: https://github.com/gephi/gephi-plugins/pull/144
